name: qGP-WorldGuard
version: '${project.version}'
main: gg.quartzdev.qgpworldguard.QGPWorldGuard
api-version: '1.21'
dependencies:
  server:
    GriefPrevention:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: true